### ISSUE TITLE
Search for OL to include also OL-atlets

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#172]
search for OL returns this from six days ago:

<img width="948" alt="image" src="https://github.com/user-attachments/assets/89c40aa8-e6ba-437a-923b-28901bc7cc81">

however, in the DB we have articles from 2h ago:

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/54eb0275-50b9-4a00-b297-6da765864cfc">

I guess our search is strict based on keywords. I wonder if there's an easy way to improve on this?

**Comment by tfnribeiro** [comment]
I am quite certain that that article is found by ES, but it's underprioritized due to Difficulty and scoring from the query. While recency is used in the query, with the latest updates we made to the way we score articles, searching doesn't prioritize recency as much VS the difficulty and relevance. 

That article doesn't have that much of the OL keyword, so it's under prioritized VS other articles, simply based on the keyword search "OL": 3 ocurrences, VS  6 ocurrences of the Holger Rune Article.

I would argue that for Klara's idea of searching latest articles then we could remove the difficulty filter, but then again if you are a A1-A2 learner would you really want to see a C1 article being recommended?  My recommendations are also different (C1 level):

![image](https://github.com/user-attachments/assets/51c2453b-d4f9-4ec2-bf26-fafafbbf0066)
